In [1]:
import os
os.chdir("D:/Projects/volatility-radar")

In [2]:
import numpy as np
import pandas as pd

df = pd.read_csv("data/processed/full_labeled.csv")
df.head()

,date,time,currency,event,impact,pair,open,high,low,close,actual,previous,surprise,impact_score,label,rolling_std,return
0,2021-01-15,1:15pm,EUR,French Final CPI m/m,Low,EURUSD,1.21540,1.21625,1.2072,1.20749,2.000000e-01,2.000000e-01,0.000000e+00,1,5,0.425123,-0.650815
1,2021-01-15,1:15pm,EUR,French Gov Budget Balance,Low,EURUSD,1.21540,1.21625,1.2072,1.20749,-1.768000e+11,-1.599000e+11,-1.690000e+10,1,5,0.425123,-0.650815
2,2021-01-15,3:30pm,EUR,Trade Balance,Low,EURUSD,1.21540,1.21625,1.2072,1.20749,2.510000e+10,2.520000e+10,-1.000000e+08,1,5,0.425123,-0.650815
3,2021-01-19,12:30pm,EUR,German Final CPI m/m,Low,EURUSD,1.20744,1.21450,1.2072,1.21280,5.000000e-01,5.000000e-01,0.000000e+00,1,2,0.441962,0.443914
4,2021-01-19,2:30pm,EUR,Current Account,Low,EURUSD,1.20744,1.21450,1.2072,1.21280,2.460000e+10,2.560000e+10,-1.000000e+09,1,2,0.441962,0.443914

In [3]:
df.dtypes

date                str
time                str
currency            str
event               str
impact              str
pair                str
open            float64
high            float64
low             float64
close           float64
actual          float64
previous        float64
surprise        float64
impact_score      int64
label             int64
rolling_std     float64
return          float64
dtype: object

In [4]:
df['date'] = pd.to_datetime(df['date'] )

In [5]:
df[df['pair'] == 'EURUSD'].head(10)

,date,time,currency,event,impact,pair,open,high,low,close,actual,previous,surprise,impact_score,label,rolling_std,return
0,2021-01-15,1:15pm,EUR,French Final CPI m/m,Low,EURUSD,1.21540,1.21625,1.2072,1.20749,2.000000e-01,2.000000e-01,0.000000e+00,1,5,0.425123,-0.650815
1,2021-01-15,1:15pm,EUR,French Gov Budget Balance,Low,EURUSD,1.21540,1.21625,1.2072,1.20749,-1.768000e+11,-1.599000e+11,-1.690000e+10,1,5,0.425123,-0.650815
2,2021-01-15,3:30pm,EUR,Trade Balance,Low,EURUSD,1.21540,1.21625,1.2072,1.20749,2.510000e+10,2.520000e+10,-1.000000e+08,1,5,0.425123,-0.650815
3,2021-01-19,12:30pm,EUR,German Final CPI m/m,Low,EURUSD,1.20744,1.21450,1.2072,1.21280,5.000000e-01,5.000000e-01,0.000000e+00,1,2,0.441962,0.443914
4,2021-01-19,2:30pm,EUR,Current Account,Low,EURUSD,1.20744,1.21450,1.2072,1.21280,2.460000e+10,2.560000e+10,-1.000000e+09,1,2,0.441962,0.443914
5,2021-01-19,2:30pm,EUR,Italian Trade Balance,Low,EURUSD,1.20744,1.21450,1.2072,1.21280,6.770000e+09,7.580000e+09,-8.100000e+08,1,2,0.441962,0.443914
6,2021-01-19,3:30pm,EUR,ZEW Economic Sentiment,Low,EURUSD,1.20744,1.21450,1.2072,1.21280,5.830000e+01,5.440000e+01,3.900000e+00,1,2,0.441962,0.443914
7,2021-01-19,3:30pm,EUR,German ZEW Economic Sentiment,Low,EURUSD,1.20744,1.21450,1.2072,1.21280,6.180000e+01,5.500000e+01,6.800000e+00,1,2,0.441962,0.443914
8,2021-01-20,12:30pm,EUR,German PPI m/m,Low,EURUSD,1.21284,1.21582,1.2075,1.21044,8.000000e-01,2.000000e-01,6.000000e-01,1,5,0.422319,-0.197883
9,2021-01-20,3:30pm,EUR,Final Core CPI y/y,Low,EURUSD,1.21284,1.21582,1.2075,1.21044,2.000000e-01,2.000000e-01,0.000000e+00,1,5,0.422319,-0.197883

In [6]:
f_m = pd.read_csv("data/processed/full_merged.csv")
f_m.head(100)

,date,time,currency,event,impact,actual,previous,pair,open,high,low,close
0,2021-01-04,1:45pm,EUR,Spanish Manufacturing PMI,Low,51.0,49.8,EURUSD,1.22386,1.23098,1.2229,1.22461
1,2021-01-04,2:15pm,EUR,Italian Manufacturing PMI,Low,52.8,51.5,EURUSD,1.22386,1.23098,1.2229,1.22461
2,2021-01-04,2:20pm,EUR,French Final Manufacturing PMI,Low,51.1,51.1,EURUSD,1.22386,1.23098,1.2229,1.22461
3,2021-01-04,2:25pm,EUR,German Final Manufacturing PMI,Low,58.3,58.6,EURUSD,1.22386,1.23098,1.2229,1.22461
4,2021-01-04,2:30pm,EUR,Final Manufacturing PMI,Low,55.2,55.5,EURUSD,1.22386,1.23098,1.2229,1.22461
...,...,...,...,...,...,...,...,...,...,...,...,...
95,2021-02-04,3:20pm,EUR,Spanish 10-y Bond Auction,Low,0.16|1.6,-0.03|3.0,EURUSD,1.20351,1.20430,1.1956,1.19620
96,2021-02-04,3:30pm,EUR,Retail Sales m/m,Low,2.0%,-5.7%,EURUSD,1.20351,1.20430,1.1956,1.19620
97,2021-02-04,3:38pm,EUR,French 10-y Bond Auction,Low,-0.25|2.2,-0.33|1.9,EURUSD,1.20351,1.20430,1.1956,1.19620
98,2021-02-05,12:30pm,EUR,German Factory Orders m/m,Low,-1.9%,2.7%,EURUSD,1.19618,1.20500,1.1951,1.20430
99,2021-02-05,1:15pm,EUR,French Prelim Private Payrolls q/q,Low,-0.2%,1.6%,EURUSD,1.19618,1.20500,1.1951,1.20430

In [7]:
f_m["event"].unique().value_counts()

Spanish Manufacturing PMI               1
Italian Manufacturing PMI               1
French Final Manufacturing PMI          1
German Final Manufacturing PMI          1
Final Manufacturing PMI                 1
                                       ..
Final GDP Price Index q/q               1
Consumer Credit m/m                     1
Prelim Benchmark Payrolls Revision      1
Cleveland Fed Inflation Expectations    1
ADP Weekly Employment Change            1
Name: count, Length: 210, dtype: int64

In [9]:
f_m.groupby('impact')["impact"].count()

impact
High       4606
Low       15054
Medium     3831
Name: impact, dtype: int64