In [32]:
import requests
import pandas as pd
from io import StringIO

url = "https://www.alphavantage.co/query?function=FX_DAILY&from_symbol=EUR&to_symbol=USD&interval=60min&outputsize=full&apikey=OAM1CVTXQJ5FJ21N&datatype=csv"

r  = requests.get(url)

df = pd.read_csv(StringIO(r.text))

df.head()

    timestamp    open    high     low   close
0  2026-03-13  1.1510  1.1529  1.1410  1.1416
1  2026-03-12  1.1567  1.1575  1.1508  1.1510
2  2026-03-11  1.1611  1.1645  1.1559  1.1566
3  2026-03-10  1.1636  1.1667  1.1605  1.1610
4  2026-03-09  1.1567  1.1637  1.1505  1.1636

In [30]:
print(df.columns.to_list())
print(df.dtypes)
print(df.shape)

['timestamp', 'open', 'high', 'low', 'close']
timestamp        str
open         float64
high         float64
low          float64
close        float64
dtype: object
(100, 5)

In [3]:
import pandas as pd

df = pd.read_csv("D:/Projects/volatility-radar/data/raw/economic_calendar_raw.csv", delimiter=",")

df.head()

,date,time,currency,event,impact,actual,forecast,previous
0,Mon Jan 4,6:00am,JPY,Final Manufacturing PMI,Low,50.0,49.7,49.7
1,Mon Jan 4,1:45pm,EUR,Spanish Manufacturing PMI,Low,51.0,52.6,49.8
2,Mon Jan 4,2:15pm,EUR,Italian Manufacturing PMI,Low,52.8,53.5,51.5
3,Mon Jan 4,2:20pm,EUR,French Final Manufacturing PMI,Low,51.1,51.1,51.1
4,Mon Jan 4,2:25pm,EUR,German Final Manufacturing PMI,Low,58.3,58.6,58.6

In [5]:
print(df.shape)
print(df['currency'].value_counts())
print(df["impact"].value_counts())
print(df.isnull().sum())

(13762, 8)
currency
USD    4961
EUR    4320
GBP    2581
JPY    1900
Name: count, dtype: int64
impact
Low       10092
High       1965
Medium     1705
Name: count, dtype: int64
date           0
time        5240
currency       0
event          0
impact         0
actual        43
forecast    1337
previous       1
dtype: int64